version: '3.1'

services:
  db:
    image: postgres
    container_name: driver_database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: "Driver"
    volumes:
      - ../../database/init.sql:/database_setup/init.sql
      - ../../database/init.sh:/docker-entrypoint-initdb.d/init.sh 
